<a href="https://colab.research.google.com/github/Sanjar-cloud/ai-foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.3

In [ ]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [ ]:
df.head() # default 5ta

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [15]:
print(df.tail())

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [16]:
print(df.shape)

(7, 2)

In [17]:
print(df.columns)

Index(['cars', 'counts'], dtype='object')

In [18]:
print(df.dtypes)

cars      object
counts     int64
dtype: object

In [19]:
print(df.describe())

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [20]:
print(df.iloc[0])   #print(df.iloc[0, 1]), print(df.iloc[0:3]) ,print(df.iloc[0:3])

cars      BMW
counts      3
Name: 0, dtype: object

In [21]:
print(df.loc[0])   #print(df.loc[0, "cars"]), print(df.loc[:, "counts"]), print(df.loc[0:2])

cars      BMW
counts      3
Name: 0, dtype: object

In [22]:
print(df[df["counts"] < 3])

      cars  counts
2     Ford       2
4  Ferrari       1

In [23]:
print(df["counts"].mean())

4.714285714285714

In [24]:
print(df["counts"].sum())

33

In [25]:
print(df["counts"].min())

1

In [26]:
print(df["counts"].max())

9

In [27]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

In [28]:
df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [29]:
# 13. isnull() — Bo'sh qiymatlarni aniqlash
print(df_missing.isnull())

    cars  counts
0  False   False
1  False   False
2   True    True
3  False   False
4  False   False
5   True   False
6  False    True

In [30]:
# 14. isnull().sum() — Bo'sh qiymatlarni sanash
print(df_missing.isnull().sum())

cars      2
counts    2
dtype: int64

In [31]:
# 15. dropna() — Bo'sh qiymati bor qatorlarni o'chirish
print(df_missing.dropna())

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [32]:
# 16. dropna(subset) — Faqat cars bo'sh bo'lgan qatorlarni o'chirish
print(df_missing.dropna(subset=["cars"]))

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [33]:
# 17. fillna() — Bo'sh qiymatlarni to'ldirish
print(df_missing.fillna({
    "cars": "Unknown",
    "counts": 0
}))

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  Unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  Unknown     9.0
6     Ford     0.0

In [36]:
# 18. DataFrame'ni yangilash
df_clean = df_missing.fillna({
    "cars": "Unknown",
    "counts": 0
})

In [37]:
print(df_clean)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  Unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  Unknown     9.0
6     Ford     0.0

In [44]:
# CSV faylni o'qish
# df = pd.read_csv("Titanic-Dataset.csv")


# Excel faylni o'qish
df = pd.read_excel("test.xlsx")
df.tail()

# JSON faylni o'qish
# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [42]:
df.to_excel("test.xlsx")

In [45]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [46]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']